[package]
name = "nno"
human_name = "Norwegian Nynorsk"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.nno]
filename = "nn-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-nno"
platform = "windows"
uuid = "5CA7541A-A523-4833-A03B-292368F9375B"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.nn"
package = "speller-nno"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-nno-mso"
platform = "windows"
uuid = "6BCE53FF-151A-4238-89D8-92AA9F0F7B0F"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-nno"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
